from pyChatGPT import ChatGPT

session_token = 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Kx6KdEWRWbkU0fFc.0nKQzOtB3wNe6w2E_dLyMOY804q_yng2pcEUxE1Ji2FKT3fBczrn1Ado9emmYXQTWAB5GISkx6rxsEO_TIUak-8M6lBWZqDkDBXXrR5-9vhOcADnBEr2sErBLny6A3yJHTVAeiog_Enhbm_Zy0SG72AR-fIM4AEpBUPRJM2Fv6biPcNgIUNhr-0Kn0QsWsCP5_a-p5sI9Oksiku9dEpFKIhPYCAVgnczumkdH529RSkT_CwFUEW75ESMkaBPP1P_goa5avDNZaTfAfZZRxicd8iSmDgj8I6NYf8Tsf5CTuBhjdrSqtyjTUX5eb6nZGBR6uTiDvONy9O-1EAcEhyAj_6elneo6oQ6IZ9csNhotilh1w-rcmgs9kRTCQmvL8L4EUCS28mSON7LFIwtqhTKeTQvi7bfC4RM5oI4Lr9tj3zgDAoK51EagXlJ1hA8DhGt39oVMCu2stOnTFPKeLk7Ifa-U4ItRWnyLfb3lHfMjlvVkofnlF3BNh_trSo9b7OcMhUiXWmFNWcezWx9dx2hpYSbzob0ezItAlJCLeYMjJQVRE79wy-5I2jW6DCzgr6qVH0_7R5HTK-ks6OpOmtk2hrkr91RggyRJQRWFg6pnH2b6-mOID20y0nsyT6R151DSAiWIC47FdDVyCiEEjW--OeKDfDtNfpH7-BtHERikDHL7VCxld_0QSO7_V0bAO6ChSZhKVEz8NC-FYrNeV0T4mTEkxTJKwAGKN-RqzcO7cm9ozR-VVHomwVK05mfO5n9zrDUhHZna48GxlYyvmP-ii0YFVJRmBEzQgM6U9XOWBx2sFqwQP_LkRQYRRQ1v4afYKeDF8lX-VuDuTjbB0Hz9ziVdJSX5J1IVzxwdQSNzocbC9_FK9ThCchbF6UFGoEO_1YsWmdKGxk1QrfgvP8CxLFzXIf7D-1BBHfCyv4hEpOJVo12qO68jgXbD-yrVMIOR1NlZf-RK1thfZzgvDn3pUWacgt3Noivfn5FI328LvYuI751ZZrF81asSNoJS30dLy3wQ1IvovID6PnIRltN1GDFaOQtpwttdkT48fYduXg4oHIR6mUxVnHNiJViz5Q6YKPPByN7YhA4tUnc2DPs-OgMJfh4pM0IxLP8CqGqAj2WYeH-aogGFPHG0hmCEQNJI8vs04h-7iUSktlWknOddEUf_yNeWZSvHQCRlkHa0PHCzU9thB02OZaHpW-xnLhnEbMno-lnEBPEtjdkZFi3Dbi_E-eT2RF8hMw6A2Yw5HTdbjantICTiouXxHP27imA4YUB0qCkcjy5gULMUPRFHZGY4xUhKKZeB2a7jAwJYyuoNUljPd0oplH3niULkIUS8qF_hhMeeDE4zW0Sd7XYtdl3eVUEuvvw586TmcYy77sTzx5GhQ6QsaUTkpktJwkrMUBE-42vvLXPte27nzBFqF038Lz1yxzeNh7ul75yZBTEDVuPknBVfbmvBbEXkMNIkhQbAuz9ERPTH_3AuKZApwXX5JdfdsJ_YNVtGO3Ca7_slkNker3j8CZAALEDENOB13gXLTsGxj2cTH_7pdz3zxhOFjRXwsXozef-0ApUg4prrqjL1kt5itZ9Q5EnYp8jeLn3V4pd0ypaw4kIav1lUMtXNW0oTywz7NldZDDVSPfkRgnbJOBIt9kEE9TTPiEOUekbxhXPoe57MK5gCTNIhtkUKeTV270jVbZm_1RuYbHohie_AuzMilf-h3x6Y6NYuJ4xV8nK01N1NFWcerVfR0ZzVN7oesQ0fqJEPQo8l7QmQ6asgD8bdnKRNSXZqlXXUcNtX4AOqsvqqG7N4N-tys5YxPq-TOUFnyUYagzOqQy6qdFOsGpVoPQzEJA9txPadnBqFTP0vyrNPV3i0okkWEKb0tLy4-u0n0JHUWkJMkMgqb7Z7DDmnw1jbkDlmaXl8961Pcd5DImkSsN9aEG22z0DskfpOUP-jAopcnALsxwq4QMIJZbxMEcspiMHqe9fZk4b5NxhL_8Ozaw5c9Y_09taWkhfKr8WZgf8kYtzWoRWbbZ4qTKs_fYu_Zouv2cN9OorslufsdKbLOh45KbZBEEVIY3QFKzOMuYkGHyXXBHs0GsPhQ_MHtB3CUAwlJ2lJX_Kx2BOHECctdFrAXEwszyWpOf4jOim9jVWg8Z986m7desIDrASpZFi010DaqqvYbEMrx4S-bLTdNPKsUFSZSqwpP_SbiewyLZeQTPGQX92g987J88E-IPdQT7OxVHxtARKXjFgRV_ETNSg8B0jwxIK0PPdatNHKaOPt1buaKHVb8VNN6HRzUFxgr7MHckQGDwdpi8SnznBDVVdOzfeBFOh_Z0IBJ7GQmSbwJBJPDSYjytmDybMFbrgmVWPqYS3VEJdOJ7YHQWfT-EKQX4e3qo52DKcZfZAbI0ZJ3sCmB_i_V2ADkL80m5UiDk70-2QRGrWSjVbG0jvIdWNrUCxGpPUVoeENV5uyJZVyIiiZbWFCloHDJWoQs5v9oe2j8eDVlMbn1L7kjQr5SCgep2wZFOIkg2swaH5vuS-SueMyylq9R-cf6TSZgt837nbKWKEaYl0E19YTI1fdP5JYafP0TXRERnw0fDY-q8UjCPa45pri2D21jx77a1Ht3PdEf0iDVNmeKE4CYVNaedyjJUSRF0.qCp3cGVR8_Q1fHiEeP114g'  # `__Secure-next-auth.session-token` cookie from https://chat.openai.com/chat
api = ChatGPT(session_token)  # auth with session token

# api = ChatGPT(session_token, conversation_id='some-random-uuid')  # specify conversation id
# api = ChatGPT(session_token, proxy='https://proxy.example.com:8080')  # specify proxy
# api = ChatGPT(session_token, chrome_args=['--window-size=1920,768'])  # specify chrome args
# api = ChatGPT(session_token, moderation=False)  # disable moderation
# api = ChatGPT(session_token, verbose=True)  # verbose mode (print debug messages)

# # auth with google login
# api = ChatGPT(auth_type='google', email='example@gmail.com', password='password')
# # auth with microsoft login
# api = ChatGPT(auth_type='microsoft', email='example@gmail.com', password='password')
# # auth with openai login (captcha solving using speech-to-text engine)
# api = ChatGPT(auth_type='openai', email='example@gmail.com', password='password')
# # auth with openai login (manual captcha solving)
# api = ChatGPT(
#     auth_type='openai', captcha_solver=None,
#     email='example@gmail.com', password='password'
# )
# # auth with openai login (2captcha for captcha solving)
# api = ChatGPT(
#     auth_type='openai', captcha_solver='2captcha', solver_apikey='abc',
#     email='example@gmail.com', password='password'
# )
# # reuse cookies generated by successful login before login,
# # if `login_cookies_path` does not exist, it will process logining  with `auth_type`, and save cookies to `login_cookies_path`
# # only works when `auth_type` is `openai` or `google`
# api = ChatGPT(auth_type='openai', email='example@xxx.com', password='password',
#     login_cookies_path='your_cookies_path',
# )

resp = api.send_message('tell me a joke, a funny one this time please!')
print(resp['message'])

api.reset_conversation()  # reset the conversation
api.clear_conversations()  # clear all conversations
api.refresh_chat_page()  # refresh the chat page
